### ISSUE TITLE
 Live Schedule menu of the CBC Sports addon.  It is getting the generic Check the Log error.

### ISSUE THREAD

**Issue by missjane63** [jbinkley60/plugin.video.cbc-sports#1]
Can you have a look at the Live Schedule menu of the CBC Sports addon.  It is getting the generic Check the Log error.

All the other menus (Most Recent, Highlights, Archive) are working fine.

**Comment by jbinkley60** [comment]
Thank you for the report.  I have fixed the issue and am publishing v1.0.5 of the addon to correct this error in the future.  If you want to pull v1.0.5 ahead of Kodi updating you can get it at: https://github.com/jbinkley60/plugin.video.cbc-sports
